<?xml version="1.0" encoding="utf-8"?>
<TestRun id="fbcc736c-6922-43ec-ad6a-d0bdc97ea6ed" name="NOWOWIK@PLKRK2L1C2G4M3 2025-04-18 16:58:06" runUser="JEGINTL\NOWOWIK" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2025-04-18T16:58:06.6482268+02:00" queuing="2025-04-18T16:58:06.6482271+02:00" start="2025-04-18T16:58:04.8528622+02:00" finish="2025-04-18T16:58:06.6597757+02:00" />
  <TestSettings name="default" id="14848c77-8e23-4406-9fea-2b872397701a">
    <Deployment runDeploymentRoot="NOWOWIK_PLKRK2L1C2G4M3_2025-04-18_16_58_06" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="8a7257b1-d316-43f0-ae08-ca5088e2f3ec" testId="1c536a7a-1fe1-9e5b-7ef5-df720493b26f" testName="Test.QuickTest.ThisOneFails" computerName="PLKRK2L1C2G4M3" duration="00:00:00.0011476" startTime="2025-04-18T16:58:06.5633497+02:00" endTime="2025-04-18T16:58:06.5633610+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="8a7257b1-d316-43f0-ae08-ca5088e2f3ec">
      <Output>
        <ErrorInfo>
          <Message>System.Exception : critical failure</Message>
          <StackTrace>   at Test.QuickTest.ThisOneFails() in C:\GitRepos\timesheeter\test\QuickTest.cs:line 8&#xD;
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)&#xD;
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Test.QuickTest.ThisOneFails" storage="c:\gitrepos\timesheeter\test\bin\debug\net9.0\test.dll" id="1c536a7a-1fe1-9e5b-7ef5-df720493b26f">
      <Execution id="8a7257b1-d316-43f0-ae08-ca5088e2f3ec" />
      <TestMethod codeBase="C:\GitRepos\timesheeter\test\bin\Debug\net9.0\Test.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Test.QuickTest" name="ThisOneFails" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="1c536a7a-1fe1-9e5b-7ef5-df720493b26f" executionId="8a7257b1-d316-43f0-ae08-ca5088e2f3ec" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.5.3.1+6b60a9e56a (64-bit .NET 9.0.4)&#xD;
[xUnit.net 00:00:00.35]   Discovering: Test&#xD;
[xUnit.net 00:00:00.38]   Discovered:  Test&#xD;
[xUnit.net 00:00:00.38]   Starting:    Test&#xD;
[xUnit.net 00:00:00.42]       System.Exception : critical failure&#xD;
[xUnit.net 00:00:00.42]       Stack Trace:&#xD;
[xUnit.net 00:00:00.42]         C:\GitRepos\timesheeter\test\QuickTest.cs(8,0): at Test.QuickTest.ThisOneFails()&#xD;
[xUnit.net 00:00:00.42]            at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)&#xD;
[xUnit.net 00:00:00.42]            at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)&#xD;
[xUnit.net 00:00:00.43]   Finished:    Test&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="PLKRK2L1C2G4M3" outcome="Error" timestamp="2025-04-18T16:58:06.5618585+02:00">
        <Text>[xUnit.net 00:00:00.42]     Test.QuickTest.ThisOneFails [FAIL]</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>